name: 自动生成 scripts 工具链接

run-name: ${{ github.actor }} GitHub Actions 🚀

on:
  push:
    branches:
      - master

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 使用 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Generate links
        run: |
          echo "# scripts 脚本工具链接" > scripts-links.md
          echo "" >> scripts-links.md
          
          for file in scripts/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "- [${filename%.*}]($file)" >> scripts-links.md
            fi
          done

      - name: Commit updated links
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add scripts-links.md
          git commit -m "Auto-generate scripts links [skip ci]"
          git push
